apiVersion: events.k8s.io/v1
deprecatedCount: 1
deprecatedFirstTimestamp: "2024-01-03T06:34:14Z"
deprecatedLastTimestamp: "2024-01-03T06:34:14Z"
deprecatedSource:
  component: deployment-controller
eventTime: null
kind: Event
metadata:
  creationTimestamp: "2024-01-03T06:34:14Z"
  name: katafygio.17a6c2c38be9a3de
  namespace: default
  uid: 6870db69-3eea-453b-9a47-2c66a445e014
note: Scaled up replica set katafygio-5bdff4d548 to 1
reason: ScalingReplicaSet
regarding:
  apiVersion: apps/v1
  kind: Deployment
  name: katafygio
  namespace: default
  resourceVersion: "1200553"
  uid: d71f94ac-73a0-4630-a57c-701d904e3f73
type: Normal
