apiVersion: crd.projectcalico.org/v1
kind: KubeControllersConfiguration
metadata:
  annotations:
    projectcalico.org/metadata: '{"uid":"f66765a4-187d-4208-a73f-4db3846839ca","creationTimestamp":"2023-12-27T18:11:11Z"}'
  creationTimestamp: "2023-12-27T18:11:11Z"
  name: default
spec:
  controllers:
    namespace:
      reconcilerPeriod: 5m0s
    node:
      leakGracePeriod: 15m0s
      reconcilerPeriod: 5m0s
      syncLabels: Enabled
    policy:
      reconcilerPeriod: 5m0s
    serviceAccount:
      reconcilerPeriod: 5m0s
    workloadEndpoint:
      reconcilerPeriod: 5m0s
  etcdV3CompactionPeriod: 10m0s
  healthChecks: Enabled
  logSeverityScreen: Info
  prometheusMetricsPort: 9094
