apiVersion: v1
data:
  tls_cert: |
    ${WEBHOOK_TLS_CERT}
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"tls_cert":"${WEBHOOK_TLS_CERT}\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"k8s-delete-validation-webhook-config","namespace":"default"}}
  creationTimestamp: "2023-11-07T08:36:13Z"
  name: k8s-delete-validation-webhook-config
  namespace: default
