apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"katafygio","chart":"katafygio-0.5.1","heritage":"Helm","release":"katafygio"},"name":"katafygio","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"katafygio","release":"katafygio"}},"strategy":{"type":"Recreate"},"template":{"metadata":{"labels":{"app":"katafygio","chart":"katafygio-0.5.1","heritage":"Helm","release":"katafygio"}},"spec":{"containers":[{"args":["--local-dir=/var/lib/katafygio/data","--healthcheck-port=8080","--log-level=info","--log-output=stdout","--resync-interval=300","--exclude-kind=replicasets","--exclude-kind=endpoints","--exclude-kind=events"],"image":"sharmag07/katafygio:k2","imagePullPolicy":"IfNotPresent","name":"katafygio","ports":[{"containerPort":8080,"name":"http","protocol":"TCP"}],"resources":{},"volumeMounts":[{"mountPath":"/var/lib/katafygio/data","name":"katafygio-data"}]}],"securityContext":{"fsGroup":65534},"serviceAccountName":"katafygio","volumes":[{"name":"katafygio-data","persistentVolumeClaim":{"claimName":"katafygio"}}]}}}}
    meta.helm.sh/release-name: katafygio
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2023-10-26T08:14:20Z"
  labels:
    app: katafygio
    app.kubernetes.io/managed-by: Helm
    chart: katafygio-0.5.1
    heritage: Helm
    release: katafygio
  name: katafygio
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: katafygio
      release: katafygio
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: katafygio
        chart: katafygio-0.5.1
        heritage: Helm
        release: katafygio
    spec:
      containers:
      - args:
        - --local-dir=/var/lib/katafygio/data
        - --healthcheck-port=8080
        - --log-level=info
        - --log-output=stdout
        - --resync-interval=300
        - --exclude-kind=replicasets
        - --exclude-kind=endpoints
        - --exclude-kind=events
        image: sharmag07/katafygio:k2
        imagePullPolicy: IfNotPresent
        name: katafygio
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/katafygio/data
          name: katafygio-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 65534
      serviceAccount: katafygio
      serviceAccountName: katafygio
      terminationGracePeriodSeconds: 30
      volumes:
      - name: katafygio-data
        persistentVolumeClaim:
          claimName: katafygio
