action: Binding
apiVersion: v1
eventTime: "2024-01-03T06:34:14.143791Z"
firstTimestamp: null
involvedObject:
  apiVersion: v1
  kind: Pod
  name: katafygio-5bdff4d548-jcbng
  namespace: default
  resourceVersion: "1200557"
  uid: 396a553e-77b8-4d0f-82f6-b95c0b0a9f07
kind: Event
lastTimestamp: null
message: Successfully assigned default/katafygio-5bdff4d548-jcbng to minikube
metadata:
  creationTimestamp: "2024-01-03T06:34:14Z"
  name: katafygio-5bdff4d548-jcbng.17a6c2c38cda51a3
  namespace: default
reason: Scheduled
reportingComponent: default-scheduler
reportingInstance: default-scheduler-minikube
source: {}
type: Normal
