apiVersion: v1
count: 42
eventTime: null
firstTimestamp: "2024-01-02T17:27:50Z"
involvedObject:
  apiVersion: v1
  kind: Pod
  name: k8s-delete-validation-webhook-789d9cf956-slfpz
  namespace: default
  resourceVersion: "864640"
  uid: b68c7b56-0901-4708-8703-659cd8de4484
kind: Event
lastTimestamp: "2024-01-03T06:30:40Z"
message: 'Unable to attach or mount volumes: unmounted volumes=[ssl-keys], unattached
  volumes=[], failed to process volumes=[]: timed out waiting for the condition'
metadata:
  creationTimestamp: "2024-01-02T17:27:50Z"
  name: k8s-delete-validation-webhook-789d9cf956-slfpz.17a697d9da75a6ac
  namespace: default
reason: FailedMount
reportingComponent: ""
reportingInstance: ""
source:
  component: kubelet
  host: minikube
type: Warning
