apiVersion: events.k8s.io/v1
deprecatedCount: 1
deprecatedFirstTimestamp: "2024-01-03T06:34:13Z"
deprecatedLastTimestamp: "2024-01-03T06:34:13Z"
deprecatedSource:
  component: replicaset-controller
eventTime: null
kind: Event
metadata:
  creationTimestamp: "2024-01-03T06:34:13Z"
  name: katafygio-797fbcd6bf.17a6c2c35c04c333
  namespace: default
note: 'Deleted pod: katafygio-797fbcd6bf-cp2rt'
reason: SuccessfulDelete
regarding:
  apiVersion: apps/v1
  kind: ReplicaSet
  name: katafygio-797fbcd6bf
  namespace: default
  resourceVersion: "1200545"
  uid: 2b3fff8c-d2d1-400f-9288-aad18298d091
type: Normal
