apiVersion: apps/v1
kind: ReplicaSet
metadata:
  annotations:
    deployment.kubernetes.io/desired-replicas: "1"
    deployment.kubernetes.io/max-replicas: "1"
    deployment.kubernetes.io/revision: "2"
    meta.helm.sh/release-name: katafygio
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2024-01-02T16:14:49Z"
  labels:
    app: katafygio
    chart: katafygio-0.5.1
    heritage: Helm
    pod-template-hash: 797fbcd6bf
    release: katafygio
  name: katafygio-797fbcd6bf
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: Deployment
    name: katafygio
    uid: d71f94ac-73a0-4630-a57c-701d904e3f73
spec:
  replicas: 0
  selector:
    matchLabels:
      app: katafygio
      pod-template-hash: 797fbcd6bf
      release: katafygio
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: katafygio
        chart: katafygio-0.5.1
        heritage: Helm
        pod-template-hash: 797fbcd6bf
        release: katafygio
    spec:
      containers:
      - args:
        - --local-dir=/var/lib/katafygio/data
        - --healthcheck-port=8080
        - --log-level=info
        - --log-output=stdout
        - --resync-interval=300
        - --exclude-kind=replicasets
        - --exclude-kind=endpoints
        - --exclude-kind=events
        image: sharmag07/katafygio:k1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: http
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        name: katafygio
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: http
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 10
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/katafygio/data
          name: katafygio-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 65534
      serviceAccount: katafygio
      serviceAccountName: katafygio
      terminationGracePeriodSeconds: 30
      volumes:
      - name: katafygio-data
        persistentVolumeClaim:
          claimName: katafygio
