apiVersion: v1
kind: Endpoints
metadata:
  annotations:
    endpoints.kubernetes.io/last-change-trigger-time: "2024-01-02T17:26:55Z"
  creationTimestamp: "2024-01-02T05:31:56Z"
  name: webhook-service
  namespace: metallb-system
subsets:
- addresses:
  - ip: 10.244.0.120
    nodeName: minikube
    targetRef:
      kind: Pod
      name: controller-595f88d88f-vzh8v
      namespace: metallb-system
      uid: ba0eb06a-abf9-4545-b945-8959f7317a30
  ports:
  - port: 9443
    protocol: TCP
