apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2023-10-26T04:58:07Z"
  generateName: kube-backups-katafygio-6fb6f8dd4-
  labels:
    app: katafygio
    chart: katafygio-0.5.1
    heritage: Helm
    pod-template-hash: 6fb6f8dd4
    release: kube-backups
  name: kube-backups-katafygio-6fb6f8dd4-jw2qk
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: kube-backups-katafygio-6fb6f8dd4
    uid: 6144015b-6f4e-4c0f-94a2-78bf8a1cbd8a
  uid: 377a9620-90fa-4ba0-8a1d-a59d4396826b
spec:
  containers:
  - args:
    - --local-dir=/var/lib/katafygio/data
    - --healthcheck-port=8080
    - --log-level=info
    - --log-output=stdout
    - --resync-interval=300
    - --exclude-kind=replicasets
    - --exclude-kind=endpoints
    - --exclude-kind=events
    image: bpineau/katafygio:v0.8.3
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /health
        port: http
        scheme: HTTP
      initialDelaySeconds: 60
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 10
    name: katafygio
    ports:
    - containerPort: 8080
      name: http
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /health
        port: http
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 10
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/lib/katafygio/data
      name: kube-backups-katafygio-data
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-fvchv
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: minikube
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 65534
  serviceAccount: kube-backups-katafygio
  serviceAccountName: kube-backups-katafygio
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-backups-katafygio-data
    persistentVolumeClaim:
      claimName: kube-backups-katafygio
  - name: kube-api-access-fvchv
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-10-26T04:58:59Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-01-02T17:25:52Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-01-02T17:25:52Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2023-10-26T04:58:59Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://2c4e0f737e50ce0c3f5966cd8b863abd5f958fc354ef75c18cfe30ccc1b007d8
    image: bpineau/katafygio:v0.8.3
    imageID: docker-pullable://bpineau/katafygio@sha256:71ffb0eed81e0b4a63670436e214493132136389dc27526efdd076825b48c786
    lastState:
      terminated:
        containerID: docker://50cc442866f3c40a9041a168b0ff092cccb1d5c74a5a3d9f134aed187387b83d
        exitCode: 0
        finishedAt: "2024-01-02T17:23:31Z"
        reason: Completed
        startedAt: "2024-01-02T05:30:21Z"
    name: katafygio
    ready: true
    restartCount: 6
    started: true
    state:
      running:
        startedAt: "2024-01-02T17:25:50Z"
  hostIP: 192.168.49.2
  phase: Running
  podIP: 10.244.0.119
  podIPs:
  - ip: 10.244.0.119
  qosClass: BestEffort
  startTime: "2023-10-26T04:58:59Z"
