apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/config.hash: eb675835e10503c79265cf0e2983f93c
    kubernetes.io/config.mirror: eb675835e10503c79265cf0e2983f93c
    kubernetes.io/config.seen: "2023-09-01T13:06:14.650384299Z"
    kubernetes.io/config.source: file
  creationTimestamp: "2023-09-01T13:06:14Z"
  labels:
    component: kube-scheduler
    tier: control-plane
  name: kube-scheduler-minikube
  namespace: kube-system
  ownerReferences:
  - apiVersion: v1
    controller: true
    kind: Node
    name: minikube
    uid: 7430868f-dbf0-4399-916e-ec5f730ad7fc
  uid: c7acbbe6-e330-47c9-bf8f-c6f189ea561d
spec:
  containers:
  - command:
    - kube-scheduler
    - --authentication-kubeconfig=/etc/kubernetes/scheduler.conf
    - --authorization-kubeconfig=/etc/kubernetes/scheduler.conf
    - --bind-address=127.0.0.1
    - --kubeconfig=/etc/kubernetes/scheduler.conf
    - --leader-elect=false
    image: registry.k8s.io/kube-scheduler:v1.27.4
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 8
      httpGet:
        host: 127.0.0.1
        path: /healthz
        port: 10259
        scheme: HTTPS
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 15
    name: kube-scheduler
    resources:
      requests:
        cpu: 100m
    startupProbe:
      failureThreshold: 24
      httpGet:
        host: 127.0.0.1
        path: /healthz
        port: 10259
        scheme: HTTPS
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 15
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/kubernetes/scheduler.conf
      name: kubeconfig
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostNetwork: true
  nodeName: minikube
  preemptionPolicy: PreemptLowerPriority
  priority: 2000001000
  priorityClassName: system-node-critical
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    seccompProfile:
      type: RuntimeDefault
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    operator: Exists
  volumes:
  - hostPath:
      path: /etc/kubernetes/scheduler.conf
      type: FileOrCreate
    name: kubeconfig
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-01-02T17:25:43Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-01-02T17:25:59Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-01-02T17:25:59Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-01-02T17:25:43Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://22076edf25dc9206d27f768684c3f448687a629f1697085384c1063460c1f75a
    image: registry.k8s.io/kube-scheduler:v1.27.4
    imageID: docker-pullable://registry.k8s.io/kube-scheduler@sha256:5897d7a97d23dce25cbf36fcd6e919180a8ef904bf5156583ffdb6a733ab04af
    lastState:
      terminated:
        containerID: docker://553323caaf02a535aa7a0c29586444f8805048d5176b40af4b7fbd9b5c697b99
        exitCode: 1
        finishedAt: "2024-01-02T17:23:31Z"
        reason: Error
        startedAt: "2024-01-02T05:30:17Z"
    name: kube-scheduler
    ready: true
    restartCount: 14
    started: true
    state:
      running:
        startedAt: "2024-01-02T17:25:44Z"
  hostIP: 192.168.49.2
  phase: Running
  podIP: 192.168.49.2
  podIPs:
  - ip: 192.168.49.2
  qosClass: Burstable
  startTime: "2024-01-02T17:25:43Z"
